export const myData = {
  firstData: [
    {
      id: "123400",
      first_name: "Haddis",
      last_name: "Fanta",
      email: "haddisfun@gmail.com",
      pro: "Web Developer",
    },
    {
      id: "123401",
      first_name: "Menelik",
      last_name: "H/Melekot",
      email: "menelik@gmail.com",
      pro: "Android Developer",
    },
    {
      id: "123402",
      first_name: "Kalkidan",
      last_name: "Mogess",
      email: "kalkidan@gmail.com",
      pro: "Accountant",
    },
    {
      id: "123403",
      first_name: "Guni",
      last_name: "Dessalegn",
      email: "guni19@gmail.com",
      pro: "MOM",
    },
    {
      id: "123400",
      first_name: "Haddis",
      last_name: "Fanta",
      email: "haddisfun@gmail.com",
      pro: "Web Developer",
    },
    {
      id: "123401",
      first_name: "Menelik",
      last_name: "H/Melekot",
      email: "menelik@gmail.com",
      pro: "Android Developer",
    },
    {
      id: "123402",
      first_name: "Kalkidan",
      last_name: "Mogess",
      email: "kalkidan@gmail.com",
      pro: "Accountant",
    },
    {
      id: "123403",
      first_name: "Guni",
      last_name: "Dessalegn",
      email: "guni19@gmail.com",
      pro: "MOM",
    },
    {
      id: "123400",
      first_name: "Haddis",
      last_name: "Fanta",
      email: "haddisfun@gmail.com",
      pro: "Web Developer",
    },
    {
      id: "123401",
      first_name: "Menelik",
      last_name: "H/Melekot",
      email: "menelik@gmail.com",
      pro: "Android Developer",
    },
    {
      id: "123402",
      first_name: "Kalkidan",
      last_name: "Mogess",
      email: "kalkidan@gmail.com",
      pro: "Accountant",
    },
    {
      id: "123403",
      first_name: "Guni",
      last_name: "Dessalegn",
      email: "guni19@gmail.com",
      pro: "MOM",
    },
    {
      id: "123400",
      first_name: "Haddis",
      last_name: "Fanta",
      email: "haddisfun@gmail.com",
      pro: "Web Developer",
    },
    {
      id: "123401",
      first_name: "Menelik",
      last_name: "H/Melekot",
      email: "menelik@gmail.com",
      pro: "Android Developer",
    },
    {
      id: "123402",
      first_name: "Kalkidan",
      last_name: "Mogess",
      email: "kalkidan@gmail.com",
      pro: "Accountant",
    },
    {
      id: "123403",
      first_name: "Guni",
      last_name: "Dessalegn",
      email: "guni19@gmail.com",
      pro: "MOM",
    },
    {
      id: "123400",
      first_name: "Haddis",
      last_name: "Fanta",
      email: "haddisfun@gmail.com",
      pro: "Web Developer",
    },
    {
      id: "123401",
      first_name: "Menelik",
      last_name: "H/Melekot",
      email: "menelik@gmail.com",
      pro: "Android Developer",
    },
    {
      id: "123402",
      first_name: "Kalkidan",
      last_name: "Mogess",
      email: "kalkidan@gmail.com",
      pro: "Accountant",
    },
    {
      id: "123403",
      first_name: "Guni",
      last_name: "Dessalegn",
      email: "guni19@gmail.com",
      pro: "MOM",
    },
    {
      id: "123400",
      first_name: "Haddis",
      last_name: "Fanta",
      email: "haddisfun@gmail.com",
      pro: "Web Developer",
    },
    {
      id: "123401",
      first_name: "Menelik",
      last_name: "H/Melekot",
      email: "menelik@gmail.com",
      pro: "Android Developer",
    },
    {
      id: "123402",
      first_name: "Kalkidan",
      last_name: "Mogess",
      email: "kalkidan@gmail.com",
      pro: "Accountant",
    },
    {
      id: "123403",
      first_name: "Guni",
      last_name: "Dessalegn",
      email: "guni19@gmail.com",
      pro: "MOM",
    },
    {
      id: "123400",
      first_name: "Haddis",
      last_name: "Fanta",
      email: "haddisfun@gmail.com",
      pro: "Web Developer",
    },
    {
      id: "123401",
      first_name: "Menelik",
      last_name: "H/Melekot",
      email: "menelik@gmail.com",
      pro: "Android Developer",
    },
    {
      id: "123402",
      first_name: "Kalkidan",
      last_name: "Mogess",
      email: "kalkidan@gmail.com",
      pro: "Accountant",
    },
    {
      id: "123403",
      first_name: "Guni",
      last_name: "Dessalegn",
      email: "guni19@gmail.com",
      pro: "MOM",
    },
    {
      id: "123400",
      first_name: "Haddis",
      last_name: "Fanta",
      email: "haddisfun@gmail.com",
      pro: "Web Developer",
    },
    {
      id: "123401",
      first_name: "Menelik",
      last_name: "H/Melekot",
      email: "menelik@gmail.com",
      pro: "Android Developer",
    },
    {
      id: "123402",
      first_name: "Kalkidan",
      last_name: "Mogess",
      email: "kalkidan@gmail.com",
      pro: "Accountant",
    },
    {
      id: "123403",
      first_name: "Guni",
      last_name: "Dessalegn",
      email: "guni19@gmail.com",
      pro: "MOM",
    },
    {
      id: "123400",
      first_name: "Haddis",
      last_name: "Fanta",
      email: "haddisfun@gmail.com",
      pro: "Web Developer",
    },
    {
      id: "123401",
      first_name: "Menelik",
      last_name: "H/Melekot",
      email: "menelik@gmail.com",
      pro: "Android Developer",
    },
    {
      id: "123402",
      first_name: "Kalkidan",
      last_name: "Mogess",
      email: "kalkidan@gmail.com",
      pro: "Accountant",
    },
    {
      id: "123403",
      first_name: "Guni",
      last_name: "Dessalegn",
      email: "guni19@gmail.com",
      pro: "MOM",
    },
    {
      id: "123400",
      first_name: "Haddis",
      last_name: "Fanta",
      email: "haddisfun@gmail.com",
      pro: "Web Developer",
    },
    {
      id: "123401",
      first_name: "Menelik",
      last_name: "H/Melekot",
      email: "menelik@gmail.com",
      pro: "Android Developer",
    },
    {
      id: "123402",
      first_name: "Kalkidan",
      last_name: "Mogess",
      email: "kalkidan@gmail.com",
      pro: "Accountant",
    },
    {
      id: "123403",
      first_name: "Guni",
      last_name: "Dessalegn",
      email: "guni19@gmail.com",
      pro: "MOM",
    },
    {
      id: "123400",
      first_name: "Haddis",
      last_name: "Fanta",
      email: "haddisfun@gmail.com",
      pro: "Web Developer",
    },
    {
      id: "123401",
      first_name: "Menelik",
      last_name: "H/Melekot",
      email: "menelik@gmail.com",
      pro: "Android Developer",
    },
    {
      id: "123402",
      first_name: "Kalkidan",
      last_name: "Mogess",
      email: "kalkidan@gmail.com",
      pro: "Accountant",
    },
    {
      id: "123403",
      first_name: "Guni",
      last_name: "Dessalegn",
      email: "guni19@gmail.com",
      pro: "MOM",
    },
  ],
};
