export const dataFiles = {
  students: [
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Surafel",
      last_name: "Fanta",
      department: "Computer Enginnering",
      nation: "Canadian",
    },
    {
      first_name: "Seble",
      last_name: "Molla",
      department: "Artist Design",
      nation: "Eritrian",
    },
    {
      first_name: "Bizuayehu",
      last_name: "Demisie",
      department: "Musical Art",
      nation: "American",
    },
    {
      first_name: "Hirut",
      last_name: "Bekele",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Surafel",
      last_name: "Fanta",
      department: "Computer Enginnering",
      nation: "Canadian",
    },
    {
      first_name: "Seble",
      last_name: "Molla",
      department: "Artist Design",
      nation: "Eritrian",
    },
    {
      first_name: "Bizuayehu",
      last_name: "Demisie",
      department: "Musical Art",
      nation: "American",
    },
    {
      first_name: "Hirut",
      last_name: "Bekele",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Surafel",
      last_name: "Fanta",
      department: "Computer Enginnering",
      nation: "Canadian",
    },
    {
      first_name: "Seble",
      last_name: "Molla",
      department: "Artist Design",
      nation: "Eritrian",
    },
    {
      first_name: "Bizuayehu",
      last_name: "Demisie",
      department: "Musical Art",
      nation: "American",
    },
    {
      first_name: "Hirut",
      last_name: "Bekele",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Surafel",
      last_name: "Fanta",
      department: "Computer Enginnering",
      nation: "Canadian",
    },
    {
      first_name: "Seble",
      last_name: "Molla",
      department: "Artist Design",
      nation: "Eritrian",
    },
    {
      first_name: "Bizuayehu",
      last_name: "Demisie",
      department: "Musical Art",
      nation: "American",
    },
    {
      first_name: "Hirut",
      last_name: "Bekele",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Surafel",
      last_name: "Fanta",
      department: "Computer Enginnering",
      nation: "Canadian",
    },
    {
      first_name: "Seble",
      last_name: "Molla",
      department: "Artist Design",
      nation: "Eritrian",
    },
    {
      first_name: "Bizuayehu",
      last_name: "Demisie",
      department: "Musical Art",
      nation: "American",
    },
    {
      first_name: "Hirut",
      last_name: "Bekele",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Surafel",
      last_name: "Fanta",
      department: "Computer Enginnering",
      nation: "Canadian",
    },
    {
      first_name: "Seble",
      last_name: "Molla",
      department: "Artist Design",
      nation: "Eritrian",
    },
    {
      first_name: "Bizuayehu",
      last_name: "Demisie",
      department: "Musical Art",
      nation: "American",
    },
    {
      first_name: "Hirut",
      last_name: "Bekele",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Surafel",
      last_name: "Fanta",
      department: "Computer Enginnering",
      nation: "Canadian",
    },
    {
      first_name: "Seble",
      last_name: "Molla",
      department: "Artist Design",
      nation: "Eritrian",
    },
    {
      first_name: "Bizuayehu",
      last_name: "Demisie",
      department: "Musical Art",
      nation: "American",
    },
    {
      first_name: "Hirut",
      last_name: "Bekele",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Surafel",
      last_name: "Fanta",
      department: "Computer Enginnering",
      nation: "Canadian",
    },
    {
      first_name: "Seble",
      last_name: "Molla",
      department: "Artist Design",
      nation: "Eritrian",
    },
    {
      first_name: "Bizuayehu",
      last_name: "Demisie",
      department: "Musical Art",
      nation: "American",
    },
    {
      first_name: "Hirut",
      last_name: "Bekele",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zewoditu",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
    {
      first_name: "Haddis",
      last_name: "Fanta",
      department: "Software Enginnering",
      nation: "Ethiopian",
    },
    {
      first_name: "Kalkidan",
      last_name: "Mogess",
      department: "Chemical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Mulatu",
      last_name: "Astatkie",
      department: "Mechanical Enginnering",
      nation: "Egyptian",
    },
    {
      first_name: "Hana",
      last_name: "Teshome",
      department: "Accounting",
      nation: "Ethiopian",
    },
    {
      first_name: "Abebe",
      last_name: "Tafere",
      department: "Software Enginnering",
      nation: "Russsian",
    },
    {
      first_name: "Menelik",
      last_name: "H/Melekot",
      department: "Mechanical Enginnering",
      nation: "Eritrian",
    },
    {
      first_name: "Zedingle",
      last_name: "Menelik",
      department: "Bussiness Adminstration",
      nation: "Ethiopian",
    },
  ],
};
